---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "solr.fullname" . }}
  labels:
{{ include "solr.common.labels" . | indent 4 }}
    app.kubernetes.io/component: server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "solr.name" . }}"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
      app.kubernetes.io/component: "server"
  serviceName: {{ include "solr.headless-service-name" . }}
  replicas: {{ .Values.replicaCount }}
  updateStrategy:
    {{ toYaml .Values.updateStrategy | indent 4}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ include "solr.name" . }}"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        app.kubernetes.io/component: "server"
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
    spec:
{{- include "solr.imagePullSecrets" . | indent 6 }}
      {{- if .Values.schedulerName }}
      schedulerName: "{{ .Values.schedulerName }}"
      {{- end }}
      securityContext:
        fsGroup: 8983
        runAsUser: 8983
      affinity:
{{ tpl (toYaml .Values.affinity) .  | indent 8 }}
      tolerations:
{{ tpl (toYaml .Values.tolerations) .  | indent 8 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      volumes:
{{- if .Values.tls.enabled }}
        - name: keystore-volume
          emptyDir: {}
        - name: "tls-secret"
          secret:
            secretName: {{ .Values.tls.certSecret.name }}
{{- if not (eq .Values.tls.caSecret.name  "") }}
        - name: "tls-ca"
          secret:
            secretName: {{ .Values.tls.caSecret.name }}
{{- end }}
{{- end }}
        - name: configs
          persistentVolumeClaim:
            claimName: solr-configs
        - name: default
          configMap:
            name: default
        - name: default-conf
          configMap:
            name: default-conf
        - name: default-lang
          configMap:
            name: default-lang
        - name: solr
          configMap:
            name: solr
      initContainers:
        - name: "configure-pvc"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          command:
            - "sh"
            - "-c"
            - |
              mkdir /tmp/configs/default
              mkdir /tmp/configs/default/conf
              mkdir /tmp/configs/default/lang
              mkdir /tmp/configs/default/data
              cp -L /tmp/solr/solr.xml /tmp/configs
              cp -L /tmp/solr/zoo.cfg /tmp/configs
              cp -L -r /tmp/default/core.properties /tmp/configs/default
              cp -L -r /tmp/default/managed-schema /tmp/configs/default
              cp -L -r /tmp/default/params.json /tmp/configs/default
              cp -L -r /tmp/default/protwords.txt /tmp/configs/default
              cp -L -r /tmp/default/solrconfig.xml /tmp/configs/default
              cp -L -r /tmp/default/stopwords.txt /tmp/configs/default
              cp -L -r /tmp/default/synonyms.txt /tmp/configs/default
              cp -L -r /tmp/default-conf/managed-schema /tmp/configs/default/conf
              cp -L -r /tmp/default-lang/*.txt /tmp/configs/default/lang
          volumeMounts:
          - name: "default"
            mountPath: "/tmp/default"
          - name: "default-conf"
            mountPath: "/tmp/default-conf"
          - name: "default-lang"
            mountPath: "/tmp/default-lang"
          - name: "configs"
            mountPath: "/tmp/configs"
          - name: "solr"
            mountPath: "/tmp/solr"
      {{- if .Values.tls.enabled }}
        - name: "setup-keystore-and-properties"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          command:
            - "sh"
            - "-c"
            - |
              set -e
              PKCS12_OUTPUT=/tmp/keystore.pkcs12
              DEST_KEYSTORE="/tmp/keystore/solr.jks"
              TRUST_KEYSTORE="/tmp/keystore/solr-truststore.jks"
              PASSWORD={{ .Values.tls.keystorePassword }}
              openssl "pkcs12" -export -inkey "/tmp/tls_secret/{{.Values.tls.certSecret.keyPath }}" -in "/tmp/tls_secret/{{.Values.tls.certSecret.certPath }}" -out "${PKCS12_OUTPUT}" -password "pass:${PASSWORD}"
              keytool -importkeystore -noprompt -srckeystore "${PKCS12_OUTPUT}" -srcstoretype "pkcs12" -destkeystore "${DEST_KEYSTORE}" -storepass "${PASSWORD}" -srcstorepass "${PASSWORD}"
{{ if .Values.tls.importKubernetesCA }}
              csplit -z -f crt- /var/run/secrets/kubernetes.io/serviceaccount/ca.crt '/-----BEGIN CERTIFICATE-----/' '{*}'
              for file in crt-*; do
                keytool -import -noprompt -keystore "${TRUST_KEYSTORE}" -file "${file}" -storepass "${PASSWORD}" -alias service-$file;
              done
              rm crt-*
{{ end }}
{{ if not (eq .Values.tls.caSecret.name "") }}
              csplit -z -f crt- /tmp/tls_ca/{{ .Values.tls.caSecret.bundlePath }} '/-----BEGIN CERTIFICATE-----/' '{*}'
              for file in crt-*; do
                keytool -import -noprompt -keystore "${TRUST_KEYSTORE}" -file "${file}" -storepass "${PASSWORD}" -alias service-$file;
              done
              rm crt-*
{{ end }}
              /opt/solr/server/scripts/cloud-scripts/zkcli.sh -zkhost "{{ include "solr.zookeeper-service-name" . }}:2181" -cmd clusterprop -name urlScheme -val https
          volumeMounts:
            - name: "keystore-volume"
              mountPath: "/tmp/keystore"
            - name: "tls-secret"
              mountPath: "/tmp/tls_secret"
              readOnly: true

{{ if not (eq .Values.tls.caSecret.name "") }}
            - name: "tls-ca"
              mountPath: "/tmp/tls_ca"
              readOnly: true
{{ end }}
{{ end }}
      containers:
        - name: solr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          ports:
            - containerPort: {{ .Values.port }}
              name: solr-client
          env:
            - name: "SOLR_JAVA_MEM"
              value: "{{ .Values.javaMem }}"
            - name: "SOLR_PORT"
              value: "{{ .Values.port }}"
            - name: "POD_HOSTNAME"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: "SOLR_HOST"
              value: "$(POD_HOSTNAME).{{ include "solr.headless-service-name" . }}.{{ .Release.Namespace }}"
            - name: "SOLR_LOG_LEVEL"
              value: "{{ .Values.logLevel }}"
{{- if .Values.extraEnvVars }}
{{ toYaml .Values.extraEnvVars | indent 12 }}
{{- end }}
{{ if .Values.tls.enabled }}
            - name: "SOLR_SSL_ENABLED"
              value: "true"
            - name: "SOLR_SSL_KEY_STORE"
              value: "/etc/ssl/keystores/solr.jks"
            - name: "SOLR_SSL_KEY_STORE_PASSWORD"
              value: "{{ .Values.tls.keystorePassword }}"
            - name: "SOLR_SSL_TRUST_STORE"
              value: "/etc/ssl/keystores/solr-truststore.jks"
            - name: "SOLR_SSL_TRUST_STORE_PASSWORD"
              value: "{{ .Values.tls.keystorePassword }}"
            - name: "SOLR_SSL_WANT_CLIENT_AUTH"
              value: "{{ .Values.tls.wantClientAuth }}"
            - name: "SOLR_SSL_NEED_CLIENT_AUTH"
              value: "{{ .Values.tls.needClientAuth }}"
            - name: "SOLR_SSL_CHECK_PEER_NAME"
              value: "{{ .Values.tls.checkPeerName }}"
{{ end }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            httpGet:
              scheme: "{{ .Values.tls.enabled | ternary "HTTPS" "HTTP" }}"
              path: /solr/admin/info/system
              port: {{ .Values.port }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            httpGet:
              scheme: "{{ .Values.tls.enabled | ternary "HTTPS" "HTTP" }}"
              path: /solr/admin/info/system
              port: {{ .Values.port }}
          volumeMounts:
            - name: configs
              mountPath: /var/solr/data
{{ if .Values.tls.enabled }}
            - name: "keystore-volume"
              mountPath: "/etc/ssl/keystores"
{{ end }}
