apiVersion: v1
kind: Service
metadata:
  name: {{ include "nbgallery.fullname" . }}
  labels:
    {{- include "nbgallery.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: gallery
      protocol: TCP
      name: http
  selector:
    {{- include "nbgallery.selectorLabels" . | nindent 4 }}
